<?xml version="1.0" encoding="ASCII"?>

<!-- oks-data version 2.2 -->


<!DOCTYPE oks-data [
  <!ELEMENT oks-data (info, (include)?, (comments)?, (obj)+)>
  <!ELEMENT info EMPTY>
  <!ATTLIST info
      name CDATA #IMPLIED
      type CDATA #IMPLIED
      num-of-items CDATA #REQUIRED
      oks-format CDATA #FIXED "data"
      oks-version CDATA #REQUIRED
      created-by CDATA #IMPLIED
      created-on CDATA #IMPLIED
      creation-time CDATA #IMPLIED
      last-modified-by CDATA #IMPLIED
      last-modified-on CDATA #IMPLIED
      last-modification-time CDATA #IMPLIED
  >
  <!ELEMENT include (file)*>
  <!ELEMENT file EMPTY>
  <!ATTLIST file
      path CDATA #REQUIRED
  >
  <!ELEMENT comments (comment)*>
  <!ELEMENT comment EMPTY>
  <!ATTLIST comment
      creation-time CDATA #REQUIRED
      created-by CDATA #REQUIRED
      created-on CDATA #REQUIRED
      author CDATA #REQUIRED
      text CDATA #REQUIRED
  >
  <!ELEMENT obj (attr | rel)*>
  <!ATTLIST obj
      class CDATA #REQUIRED
      id CDATA #REQUIRED
  >
  <!ELEMENT attr (data)*>
  <!ATTLIST attr
      name CDATA #REQUIRED
      type (bool|s8|u8|s16|u16|s32|u32|s64|u64|float|double|date|time|string|uid|enum|class|-) "-"
      val CDATA ""
  >
  <!ELEMENT data EMPTY>
  <!ATTLIST data
      val CDATA #REQUIRED
  >
  <!ELEMENT rel (ref)*>
  <!ATTLIST rel
      name CDATA #REQUIRED
      class CDATA ""
      id CDATA ""
  >
  <!ELEMENT ref EMPTY>
  <!ATTLIST ref
      class CDATA #REQUIRED
      id CDATA #REQUIRED
  >
]>

<oks-data>

<info name="" type="" num-of-items="233" oks-format="data" oks-version="oks-08-04-00-2-g4949f80 built &quot;Dec  6 2023&quot;" created-by="root" created-on="f1c9af75d018" creation-time="20240319T114528" last-modified-by="root" last-modified-on="f1c9af75d018" last-modification-time="20240319T114528"/>

<obj class="ALink" id="CustomTCMaker-2-CustomTCMakerConf-via-configuration">
 <attr name="Name" type="string" val="configuration"/>
 <rel name="From" class="Class" id="CustomTCMaker"/>
 <rel name="To" class="Class" id="CustomTCMakerConf"/>
 <rel name="Points">
  <ref class="Point" id="1 CustomTCMaker-2-CustomTCMakerConf-via-configuration"/>
  <ref class="Point" id="2 CustomTCMaker-2-CustomTCMakerConf-via-configuration"/>
  <ref class="Point" id="3 CustomTCMaker-2-CustomTCMakerConf-via-configuration"/>
  <ref class="Point" id="4 CustomTCMaker-2-CustomTCMakerConf-via-configuration"/>
 </rel>
</obj>

<obj class="ALink" id="DataReceiverConf-2-StreamEmulationParameters-via-emulation_conf">
 <attr name="Name" type="string" val="emulation_conf"/>
 <rel name="From" class="Class" id="DataReceiverConf"/>
 <rel name="To" class="Class" id="StreamEmulationParameters"/>
 <rel name="Points">
  <ref class="Point" id="1 DataReceiverConf-2-StreamEmulationParameters-via-emulation_conf"/>
  <ref class="Point" id="2 DataReceiverConf-2-StreamEmulationParameters-via-emulation_conf"/>
  <ref class="Point" id="3 DataReceiverConf-2-StreamEmulationParameters-via-emulation_conf"/>
  <ref class="Point" id="4 DataReceiverConf-2-StreamEmulationParameters-via-emulation_conf"/>
 </rel>
</obj>

<obj class="ALink" id="DataSubscriberModule-2-DataReceiverConf-via-configuration">
 <attr name="Name" type="string" val="configuration"/>
 <rel name="From" class="Class" id="DataSubscriberModule"/>
 <rel name="To" class="Class" id="DataReceiverConf"/>
 <rel name="Points">
  <ref class="Point" id="1 DataSubscriberModule-2-DataReceiverConf-via-configuration"/>
  <ref class="Point" id="2 DataSubscriberModule-2-DataReceiverConf-via-configuration"/>
  <ref class="Point" id="3 DataSubscriberModule-2-DataReceiverConf-via-configuration"/>
  <ref class="Point" id="4 DataSubscriberModule-2-DataReceiverConf-via-configuration"/>
 </rel>
</obj>

<obj class="ALink" id="FakeHSIApplication-2-FakeHSIEventGeneratorConf-via-generator">
 <attr name="Name" type="string" val="generator"/>
 <rel name="From" class="Class" id="FakeHSIApplication"/>
 <rel name="To" class="Class" id="FakeHSIEventGeneratorConf"/>
 <rel name="Points">
  <ref class="Point" id="1 FakeHSIApplication-2-FakeHSIEventGeneratorConf-via-generator"/>
  <ref class="Point" id="2 FakeHSIApplication-2-FakeHSIEventGeneratorConf-via-generator"/>
  <ref class="Point" id="3 FakeHSIApplication-2-FakeHSIEventGeneratorConf-via-generator"/>
  <ref class="Point" id="4 FakeHSIApplication-2-FakeHSIEventGeneratorConf-via-generator"/>
 </rel>
</obj>

<obj class="ALink" id="FakeHSIApplication-2-DataHandlerConf-via-link_handler">
 <attr name="Name" type="string" val="link_handler"/>
 <rel name="From" class="Class" id="FakeHSIApplication"/>
 <rel name="To" class="Class" id="DataHandlerConf"/>
 <rel name="Points">
  <ref class="Point" id="1 FakeHSIApplication-2-DataHandlerConf-via-link_handler"/>
  <ref class="Point" id="2 FakeHSIApplication-2-DataHandlerConf-via-link_handler"/>
  <ref class="Point" id="3 FakeHSIApplication-2-DataHandlerConf-via-link_handler"/>
  <ref class="Point" id="4 FakeHSIApplication-2-DataHandlerConf-via-link_handler"/>
 </rel>
</obj>

<obj class="ALink" id="HSI2TCTranslatorConf-2-HSISignalWindow-via-signals">
 <attr name="Name" type="string" val="signals"/>
 <rel name="From" class="Class" id="HSI2TCTranslatorConf"/>
 <rel name="To" class="Class" id="HSISignalWindow"/>
 <rel name="Points">
  <ref class="Point" id="1 HSI2TCTranslatorConf-2-HSISignalWindow-via-signals"/>
  <ref class="Point" id="2 HSI2TCTranslatorConf-2-HSISignalWindow-via-signals"/>
  <ref class="Point" id="3 HSI2TCTranslatorConf-2-HSISignalWindow-via-signals"/>
  <ref class="Point" id="4 HSI2TCTranslatorConf-2-HSISignalWindow-via-signals"/>
 </rel>
</obj>

<obj class="ALink" id="HSIEventToTCApplication-2-HSI2TCTranslatorConf-via-hsevent_to_tc_conf">
 <attr name="Name" type="string" val="hsevent_to_tc_conf"/>
 <rel name="From" class="Class" id="HSIEventToTCApplication"/>
 <rel name="To" class="Class" id="HSI2TCTranslatorConf"/>
 <rel name="Points">
  <ref class="Point" id="1 HSIEventToTCApplication-2-HSI2TCTranslatorConf-via-hsevent_to_tc_conf"/>
  <ref class="Point" id="2 HSIEventToTCApplication-2-HSI2TCTranslatorConf-via-hsevent_to_tc_conf"/>
  <ref class="Point" id="3 HSIEventToTCApplication-2-HSI2TCTranslatorConf-via-hsevent_to_tc_conf"/>
  <ref class="Point" id="4 HSIEventToTCApplication-2-HSI2TCTranslatorConf-via-hsevent_to_tc_conf"/>
 </rel>
</obj>

<obj class="ALink" id="MLTApplication-2-MLTConf-via-mlt_conf">
 <attr name="Name" type="string" val="mlt_conf"/>
 <rel name="From" class="Class" id="MLTApplication"/>
 <rel name="To" class="Class" id="MLTConf"/>
 <rel name="Points">
  <ref class="Point" id="1 MLTApplication-2-MLTConf-via-mlt_conf"/>
  <ref class="Point" id="2 MLTApplication-2-MLTConf-via-mlt_conf"/>
  <ref class="Point" id="3 MLTApplication-2-MLTConf-via-mlt_conf"/>
  <ref class="Point" id="4 MLTApplication-2-MLTConf-via-mlt_conf"/>
 </rel>
</obj>

<obj class="ALink" id="MLTApplication-2-StandaloneTCMakerConf-via-standalone_candidate_maker_confs">
 <attr name="Name" type="string" val="standalone_candidate_maker_confs"/>
 <rel name="From" class="Class" id="MLTApplication"/>
 <rel name="To" class="Class" id="StandaloneTCMakerConf"/>
 <rel name="Points">
  <ref class="Point" id="1 MLTApplication-2-StandaloneTCMakerConf-via-standalone_candidate_maker_confs"/>
  <ref class="Point" id="2 MLTApplication-2-StandaloneTCMakerConf-via-standalone_candidate_maker_confs"/>
  <ref class="Point" id="3 MLTApplication-2-StandaloneTCMakerConf-via-standalone_candidate_maker_confs"/>
  <ref class="Point" id="4 MLTApplication-2-StandaloneTCMakerConf-via-standalone_candidate_maker_confs"/>
 </rel>
</obj>

<obj class="ALink" id="MLTModule-2-MLTConf-via-configuration">
 <attr name="Name" type="string" val="configuration"/>
 <rel name="From" class="Class" id="MLTModule"/>
 <rel name="To" class="Class" id="MLTConf"/>
 <rel name="Points">
  <ref class="Point" id="1 MLTModule-2-MLTConf-via-configuration"/>
  <ref class="Point" id="2 MLTModule-2-MLTConf-via-configuration"/>
  <ref class="Point" id="3 MLTModule-2-MLTConf-via-configuration"/>
  <ref class="Point" id="4 MLTModule-2-MLTConf-via-configuration"/>
 </rel>
</obj>

<obj class="ALink" id="MLTModule-2-SourceIDConf-via-mandatory_links">
 <attr name="Name" type="string" val="mandatory_links"/>
 <rel name="From" class="Class" id="MLTModule"/>
 <rel name="To" class="Class" id="SourceIDConf"/>
 <rel name="Points">
  <ref class="Point" id="1 MLTModule-2-SourceIDConf-via-mandatory_links"/>
  <ref class="Point" id="2 MLTModule-2-SourceIDConf-via-mandatory_links"/>
  <ref class="Point" id="3 MLTModule-2-SourceIDConf-via-mandatory_links"/>
  <ref class="Point" id="4 MLTModule-2-SourceIDConf-via-mandatory_links"/>
 </rel>
</obj>

<obj class="ALink" id="MLTConf-2-ROIGroupConf-via-roi_group_conf">
 <attr name="Name" type="string" val="roi_group_conf"/>
 <rel name="From" class="Class" id="MLTConf"/>
 <rel name="To" class="Class" id="ROIGroupConf"/>
 <rel name="Points">
  <ref class="Point" id="1 MLTConf-2-ROIGroupConf-via-roi_group_conf"/>
  <ref class="Point" id="2 MLTConf-2-ROIGroupConf-via-roi_group_conf"/>
  <ref class="Point" id="3 MLTConf-2-ROIGroupConf-via-roi_group_conf"/>
  <ref class="Point" id="4 MLTConf-2-ROIGroupConf-via-roi_group_conf"/>
 </rel>
</obj>

<obj class="ALink" id="MLTConf-2-TCReadoutMap-via-tc_readout_map">
 <attr name="Name" type="string" val="tc_readout_map"/>
 <rel name="From" class="Class" id="MLTConf"/>
 <rel name="To" class="Class" id="TCReadoutMap"/>
 <rel name="Points">
  <ref class="Point" id="1 MLTConf-2-TCReadoutMap-via-tc_readout_map"/>
  <ref class="Point" id="2 MLTConf-2-TCReadoutMap-via-tc_readout_map"/>
  <ref class="Point" id="3 MLTConf-2-TCReadoutMap-via-tc_readout_map"/>
  <ref class="Point" id="4 MLTConf-2-TCReadoutMap-via-tc_readout_map"/>
 </rel>
</obj>

<obj class="ALink" id="RandomTCMakerModule-2-RandomTCMakerConf-via-configuration">
 <attr name="Name" type="string" val="configuration"/>
 <rel name="From" class="Class" id="RandomTCMakerModule"/>
 <rel name="To" class="Class" id="RandomTCMakerConf"/>
 <rel name="Points">
  <ref class="Point" id="1 RandomTCMakerModule-2-RandomTCMakerConf-via-configuration"/>
  <ref class="Point" id="2 RandomTCMakerModule-2-RandomTCMakerConf-via-configuration"/>
  <ref class="Point" id="3 RandomTCMakerModule-2-RandomTCMakerConf-via-configuration"/>
  <ref class="Point" id="4 RandomTCMakerModule-2-RandomTCMakerConf-via-configuration"/>
 </rel>
</obj>

<obj class="ALink" id="DataHandlerConf-2-DataProcessor-via-data_processor">
 <attr name="Name" type="string" val="data_processor"/>
 <rel name="From" class="Class" id="DataHandlerConf"/>
 <rel name="To" class="Class" id="DataProcessor"/>
 <rel name="Points">
  <ref class="Point" id="1 DataHandlerConf-2-DataProcessor-via-data_processor"/>
  <ref class="Point" id="2 DataHandlerConf-2-DataProcessor-via-data_processor"/>
  <ref class="Point" id="3 DataHandlerConf-2-DataProcessor-via-data_processor"/>
  <ref class="Point" id="4 DataHandlerConf-2-DataProcessor-via-data_processor"/>
 </rel>
</obj>

<obj class="ALink" id="DataHandlerConf-2-LatencyBuffer-via-latency_buffer">
 <attr name="Name" type="string" val="latency_buffer"/>
 <rel name="From" class="Class" id="DataHandlerConf"/>
 <rel name="To" class="Class" id="LatencyBuffer"/>
 <rel name="Points">
  <ref class="Point" id="1 DataHandlerConf-2-LatencyBuffer-via-latency_buffer"/>
  <ref class="Point" id="2 DataHandlerConf-2-LatencyBuffer-via-latency_buffer"/>
  <ref class="Point" id="3 DataHandlerConf-2-LatencyBuffer-via-latency_buffer"/>
  <ref class="Point" id="4 DataHandlerConf-2-LatencyBuffer-via-latency_buffer"/>
 </rel>
</obj>

<obj class="ALink" id="DataHandlerConf-2-RequestHandler-via-request_handler">
 <attr name="Name" type="string" val="request_handler"/>
 <rel name="From" class="Class" id="DataHandlerConf"/>
 <rel name="To" class="Class" id="RequestHandler"/>
 <rel name="Points">
  <ref class="Point" id="1 DataHandlerConf-2-RequestHandler-via-request_handler"/>
  <ref class="Point" id="2 DataHandlerConf-2-RequestHandler-via-request_handler"/>
  <ref class="Point" id="3 DataHandlerConf-2-RequestHandler-via-request_handler"/>
  <ref class="Point" id="4 DataHandlerConf-2-RequestHandler-via-request_handler"/>
 </rel>
</obj>

<obj class="ALink" id="RequestHandler-2-DataRecorderConf-via-data_recorder">
 <attr name="Name" type="string" val="data_recorder"/>
 <rel name="From" class="Class" id="RequestHandler"/>
 <rel name="To" class="Class" id="DataRecorderConf"/>
 <rel name="Points">
  <ref class="Point" id="1 RequestHandler-2-DataRecorderConf-via-data_recorder"/>
  <ref class="Point" id="2 RequestHandler-2-DataRecorderConf-via-data_recorder"/>
  <ref class="Point" id="3 RequestHandler-2-DataRecorderConf-via-data_recorder"/>
  <ref class="Point" id="4 RequestHandler-2-DataRecorderConf-via-data_recorder"/>
 </rel>
</obj>

<obj class="ALink" id="TADataProcessor-2-TCAlgorithm-via-algorithms">
 <attr name="Name" type="string" val="algorithms"/>
 <rel name="From" class="Class" id="TADataProcessor"/>
 <rel name="To" class="Class" id="TCAlgorithm"/>
 <rel name="Points">
  <ref class="Point" id="1 TADataProcessor-2-TCAlgorithm-via-algorithms"/>
  <ref class="Point" id="2 TADataProcessor-2-TCAlgorithm-via-algorithms"/>
  <ref class="Point" id="3 TADataProcessor-2-TCAlgorithm-via-algorithms"/>
  <ref class="Point" id="4 TADataProcessor-2-TCAlgorithm-via-algorithms"/>
 </rel>
</obj>

<obj class="ALink" id="TPDataProcessor-2-TAAlgorithm-via-algorithms">
 <attr name="Name" type="string" val="algorithms"/>
 <rel name="From" class="Class" id="TPDataProcessor"/>
 <rel name="To" class="Class" id="TAAlgorithm"/>
 <rel name="Points">
  <ref class="Point" id="1 TPDataProcessor-2-TAAlgorithm-via-algorithms"/>
  <ref class="Point" id="2 TPDataProcessor-2-TAAlgorithm-via-algorithms"/>
  <ref class="Point" id="3 TPDataProcessor-2-TAAlgorithm-via-algorithms"/>
  <ref class="Point" id="4 TPDataProcessor-2-TAAlgorithm-via-algorithms"/>
 </rel>
</obj>

<obj class="ALink" id="TPDataProcessor-2-TPChannelFilterConf-via-channel_filter_conf">
 <attr name="Name" type="string" val="channel_filter_conf"/>
 <rel name="From" class="Class" id="TPDataProcessor"/>
 <rel name="To" class="Class" id="TPChannelFilterConf"/>
 <rel name="Points">
  <ref class="Point" id="1 TPDataProcessor-2-TPChannelFilterConf-via-channel_filter_conf"/>
  <ref class="Point" id="2 TPDataProcessor-2-TPChannelFilterConf-via-channel_filter_conf"/>
  <ref class="Point" id="3 TPDataProcessor-2-TPChannelFilterConf-via-channel_filter_conf"/>
  <ref class="Point" id="4 TPDataProcessor-2-TPChannelFilterConf-via-channel_filter_conf"/>
 </rel>
</obj>

<obj class="ALink" id="TriggerApplication-2-DataReceiverConf-via-data_subscriber">
 <attr name="Name" type="string" val="data_subscriber"/>
 <rel name="From" class="Class" id="TriggerApplication"/>
 <rel name="To" class="Class" id="DataReceiverConf"/>
 <rel name="Points">
  <ref class="Point" id="1 TriggerApplication-2-DataReceiverConf-via-data_subscriber"/>
  <ref class="Point" id="2 TriggerApplication-2-DataReceiverConf-via-data_subscriber"/>
  <ref class="Point" id="3 TriggerApplication-2-DataReceiverConf-via-data_subscriber"/>
  <ref class="Point" id="4 TriggerApplication-2-DataReceiverConf-via-data_subscriber"/>
 </rel>
</obj>

<obj class="ALink" id="TriggerApplication-2-DataHandlerConf-via-trigger_inputs_handler">
 <attr name="Name" type="string" val="trigger_inputs_handler"/>
 <rel name="From" class="Class" id="TriggerApplication"/>
 <rel name="To" class="Class" id="DataHandlerConf"/>
 <rel name="Points">
  <ref class="Point" id="1 TriggerApplication-2-DataHandlerConf-via-trigger_inputs_handler"/>
  <ref class="Point" id="2 TriggerApplication-2-DataHandlerConf-via-trigger_inputs_handler"/>
  <ref class="Point" id="3 TriggerApplication-2-DataHandlerConf-via-trigger_inputs_handler"/>
  <ref class="Point" id="4 TriggerApplication-2-DataHandlerConf-via-trigger_inputs_handler"/>
 </rel>
</obj>

<obj class="Class" id="CustomTCMaker">
 <attr name="x" type="s16" val="1011"/>
 <attr name="y" type="s16" val="922"/>
</obj>

<obj class="Class" id="CustomTCMakerConf">
 <attr name="x" type="s16" val="69"/>
 <attr name="y" type="s16" val="847"/>
</obj>

<obj class="Class" id="DataProcessor">
 <attr name="x" type="s16" val="1068"/>
 <attr name="y" type="s16" val="334"/>
</obj>

<obj class="Class" id="DataReceiverConf">
 <attr name="x" type="s16" val="1162"/>
 <attr name="y" type="s16" val="137"/>
</obj>

<obj class="Class" id="DataRecorderConf">
 <attr name="x" type="s16" val="1754"/>
 <attr name="y" type="s16" val="15"/>
</obj>

<obj class="Class" id="DataSubscriberModule">
 <attr name="x" type="s16" val="1140"/>
 <attr name="y" type="s16" val="46"/>
</obj>

<obj class="Class" id="FakeHSIApplication">
 <attr name="x" type="s16" val="466"/>
 <attr name="y" type="s16" val="147"/>
</obj>

<obj class="Class" id="FakeHSIEventGeneratorConf">
 <attr name="x" type="s16" val="493"/>
 <attr name="y" type="s16" val="304"/>
</obj>

<obj class="Class" id="HSI2TCTranslatorConf">
 <attr name="x" type="s16" val="742"/>
 <attr name="y" type="s16" val="354"/>
</obj>

<obj class="Class" id="HSIEventToTCApplication">
 <attr name="x" type="s16" val="620"/>
 <attr name="y" type="s16" val="159"/>
</obj>

<obj class="Class" id="HSIFrameProcessor">
 <attr name="x" type="s16" val="1232"/>
 <attr name="y" type="s16" val="556"/>
</obj>

<obj class="Class" id="HSISignalWindow">
 <attr name="x" type="s16" val="900"/>
 <attr name="y" type="s16" val="417"/>
</obj>

<obj class="Class" id="LatencyBuffer">
 <attr name="x" type="s16" val="1808"/>
 <attr name="y" type="s16" val="338"/>
</obj>

<obj class="Class" id="MLTApplication">
 <attr name="x" type="s16" val="171"/>
 <attr name="y" type="s16" val="147"/>
</obj>

<obj class="Class" id="MLTModule">
 <attr name="x" type="s16" val="646"/>
 <attr name="y" type="s16" val="488"/>
</obj>

<obj class="Class" id="MLTConf">
 <attr name="x" type="s16" val="222"/>
 <attr name="y" type="s16" val="275"/>
</obj>

<obj class="Class" id="ROIGroupConf">
 <attr name="x" type="s16" val="265"/>
 <attr name="y" type="s16" val="666"/>
</obj>

<obj class="Class" id="RandomTCMakerModule">
 <attr name="x" type="s16" val="813"/>
 <attr name="y" type="s16" val="846"/>
</obj>

<obj class="Class" id="RandomTCMakerConf">
 <attr name="x" type="s16" val="401"/>
 <attr name="y" type="s16" val="808"/>
</obj>

<obj class="Class" id="RawDataProcessor">
 <attr name="x" type="s16" val="1036"/>
 <attr name="y" type="s16" val="537"/>
</obj>

<obj class="Class" id="DataHandlerConf">
 <attr name="x" type="s16" val="1403"/>
 <attr name="y" type="s16" val="265"/>
</obj>

<obj class="Class" id="RequestHandler">
 <attr name="x" type="s16" val="1761"/>
 <attr name="y" type="s16" val="169"/>
</obj>

<obj class="Class" id="SmartDaqApplication">
 <attr name="x" type="s16" val="766"/>
 <attr name="y" type="s16" val="8"/>
</obj>

<obj class="Class" id="SourceIDConf">
 <attr name="x" type="s16" val="644"/>
 <attr name="y" type="s16" val="604"/>
</obj>

<obj class="Class" id="StandaloneTCMakerModule">
 <attr name="x" type="s16" val="801"/>
 <attr name="y" type="s16" val="752"/>
</obj>

<obj class="Class" id="StandaloneTCMakerConf">
 <attr name="x" type="s16" val="66"/>
 <attr name="y" type="s16" val="564"/>
</obj>

<obj class="Class" id="StreamEmulationParameters">
 <attr name="x" type="s16" val="1456"/>
 <attr name="y" type="s16" val="50"/>
</obj>

<obj class="Class" id="TAAlgorithm">
 <attr name="x" type="s16" val="1522"/>
 <attr name="y" type="s16" val="659"/>
</obj>

<obj class="Class" id="TADataProcessor">
 <attr name="x" type="s16" val="1442"/>
 <attr name="y" type="s16" val="553"/>
</obj>

<obj class="Class" id="TCAlgorithm">
 <attr name="x" type="s16" val="1734"/>
 <attr name="y" type="s16" val="560"/>
</obj>

<obj class="Class" id="TCCustomAlgorithm">
 <attr name="x" type="s16" val="1699"/>
 <attr name="y" type="s16" val="649"/>
</obj>

<obj class="Class" id="TCReadoutMap">
 <attr name="x" type="s16" val="396"/>
 <attr name="y" type="s16" val="563"/>
</obj>

<obj class="Class" id="TPChannelFilterConf">
 <attr name="x" type="s16" val="1008"/>
 <attr name="y" type="s16" val="701"/>
</obj>

<obj class="Class" id="TPDataProcessor">
 <attr name="x" type="s16" val="1297"/>
 <attr name="y" type="s16" val="678"/>
</obj>

<obj class="Class" id="TAMakerHorizontalMuonAlgorithm">
 <attr name="x" type="s16" val="1359"/>
 <attr name="y" type="s16" val="780"/>
</obj>

<obj class="Class" id="TAMakerPrescaleAlgorithm">
 <attr name="x" type="s16" val="1627"/>
 <attr name="y" type="s16" val="783"/>
</obj>

<obj class="Class" id="TriggerApplication">
 <attr name="x" type="s16" val="804"/>
 <attr name="y" type="s16" val="152"/>
</obj>

<obj class="GLink" id="DataProcessor-2-HSIFrameProcessor">
 <rel name="From" class="Class" id="DataProcessor"/>
 <rel name="To" class="Class" id="HSIFrameProcessor"/>
 <rel name="Points">
  <ref class="Point" id="1 DataProcessor-2-HSIFrameProcessor"/>
  <ref class="Point" id="2 DataProcessor-2-HSIFrameProcessor"/>
  <ref class="Point" id="3 DataProcessor-2-HSIFrameProcessor"/>
  <ref class="Point" id="4 DataProcessor-2-HSIFrameProcessor"/>
 </rel>
</obj>

<obj class="GLink" id="DataProcessor-2-RawDataProcessor">
 <rel name="From" class="Class" id="DataProcessor"/>
 <rel name="To" class="Class" id="RawDataProcessor"/>
 <rel name="Points">
  <ref class="Point" id="1 DataProcessor-2-RawDataProcessor"/>
  <ref class="Point" id="2 DataProcessor-2-RawDataProcessor"/>
  <ref class="Point" id="3 DataProcessor-2-RawDataProcessor"/>
  <ref class="Point" id="4 DataProcessor-2-RawDataProcessor"/>
 </rel>
</obj>

<obj class="GLink" id="DataProcessor-2-TADataProcessor">
 <rel name="From" class="Class" id="DataProcessor"/>
 <rel name="To" class="Class" id="TADataProcessor"/>
 <rel name="Points">
  <ref class="Point" id="1 DataProcessor-2-TADataProcessor"/>
  <ref class="Point" id="2 DataProcessor-2-TADataProcessor"/>
  <ref class="Point" id="3 DataProcessor-2-TADataProcessor"/>
  <ref class="Point" id="4 DataProcessor-2-TADataProcessor"/>
 </rel>
</obj>

<obj class="GLink" id="DataProcessor-2-TPDataProcessor">
 <rel name="From" class="Class" id="DataProcessor"/>
 <rel name="To" class="Class" id="TPDataProcessor"/>
 <rel name="Points">
  <ref class="Point" id="1 DataProcessor-2-TPDataProcessor"/>
  <ref class="Point" id="2 DataProcessor-2-TPDataProcessor"/>
  <ref class="Point" id="3 DataProcessor-2-TPDataProcessor"/>
  <ref class="Point" id="4 DataProcessor-2-TPDataProcessor"/>
 </rel>
</obj>

<obj class="GLink" id="DataReceiverConf-2-HSI2TCTranslatorConf">
 <rel name="From" class="Class" id="DataReceiverConf"/>
 <rel name="To" class="Class" id="HSI2TCTranslatorConf"/>
 <rel name="Points">
  <ref class="Point" id="1 DataReceiverConf-2-HSI2TCTranslatorConf"/>
  <ref class="Point" id="2 DataReceiverConf-2-HSI2TCTranslatorConf"/>
  <ref class="Point" id="3 DataReceiverConf-2-HSI2TCTranslatorConf"/>
  <ref class="Point" id="4 DataReceiverConf-2-HSI2TCTranslatorConf"/>
 </rel>
</obj>

<obj class="GLink" id="SmartDaqApplication-2-FakeHSIApplication">
 <rel name="From" class="Class" id="SmartDaqApplication"/>
 <rel name="To" class="Class" id="FakeHSIApplication"/>
 <rel name="Points">
  <ref class="Point" id="1 SmartDaqApplication-2-FakeHSIApplication"/>
  <ref class="Point" id="2 SmartDaqApplication-2-FakeHSIApplication"/>
  <ref class="Point" id="3 SmartDaqApplication-2-FakeHSIApplication"/>
  <ref class="Point" id="4 SmartDaqApplication-2-FakeHSIApplication"/>
 </rel>
</obj>

<obj class="GLink" id="SmartDaqApplication-2-HSIEventToTCApplication">
 <rel name="From" class="Class" id="SmartDaqApplication"/>
 <rel name="To" class="Class" id="HSIEventToTCApplication"/>
 <rel name="Points">
  <ref class="Point" id="1 SmartDaqApplication-2-HSIEventToTCApplication"/>
  <ref class="Point" id="2 SmartDaqApplication-2-HSIEventToTCApplication"/>
  <ref class="Point" id="3 SmartDaqApplication-2-HSIEventToTCApplication"/>
  <ref class="Point" id="4 SmartDaqApplication-2-HSIEventToTCApplication"/>
 </rel>
</obj>

<obj class="GLink" id="SmartDaqApplication-2-MLTApplication">
 <rel name="From" class="Class" id="SmartDaqApplication"/>
 <rel name="To" class="Class" id="MLTApplication"/>
 <rel name="Points">
  <ref class="Point" id="1 SmartDaqApplication-2-MLTApplication"/>
  <ref class="Point" id="2 SmartDaqApplication-2-MLTApplication"/>
  <ref class="Point" id="3 SmartDaqApplication-2-MLTApplication"/>
  <ref class="Point" id="4 SmartDaqApplication-2-MLTApplication"/>
 </rel>
</obj>

<obj class="GLink" id="SmartDaqApplication-2-TriggerApplication">
 <rel name="From" class="Class" id="SmartDaqApplication"/>
 <rel name="To" class="Class" id="TriggerApplication"/>
 <rel name="Points">
  <ref class="Point" id="1 SmartDaqApplication-2-TriggerApplication"/>
  <ref class="Point" id="2 SmartDaqApplication-2-TriggerApplication"/>
  <ref class="Point" id="3 SmartDaqApplication-2-TriggerApplication"/>
  <ref class="Point" id="4 SmartDaqApplication-2-TriggerApplication"/>
 </rel>
</obj>

<obj class="GLink" id="StandaloneTCMakerModule-2-CustomTCMaker">
 <rel name="From" class="Class" id="StandaloneTCMakerModule"/>
 <rel name="To" class="Class" id="CustomTCMaker"/>
 <rel name="Points">
  <ref class="Point" id="1 StandaloneTCMakerModule-2-CustomTCMaker"/>
  <ref class="Point" id="2 StandaloneTCMakerModule-2-CustomTCMaker"/>
  <ref class="Point" id="3 StandaloneTCMakerModule-2-CustomTCMaker"/>
  <ref class="Point" id="4 StandaloneTCMakerModule-2-CustomTCMaker"/>
 </rel>
</obj>

<obj class="GLink" id="StandaloneTCMakerModule-2-RandomTCMakerModule">
 <rel name="From" class="Class" id="StandaloneTCMakerModule"/>
 <rel name="To" class="Class" id="RandomTCMakerModule"/>
 <rel name="Points">
  <ref class="Point" id="1 StandaloneTCMakerModule-2-RandomTCMakerModule"/>
  <ref class="Point" id="2 StandaloneTCMakerModule-2-RandomTCMakerModule"/>
  <ref class="Point" id="3 StandaloneTCMakerModule-2-RandomTCMakerModule"/>
  <ref class="Point" id="4 StandaloneTCMakerModule-2-RandomTCMakerModule"/>
 </rel>
</obj>

<obj class="GLink" id="StandaloneTCMakerConf-2-CustomTCMakerConf">
 <rel name="From" class="Class" id="StandaloneTCMakerConf"/>
 <rel name="To" class="Class" id="CustomTCMakerConf"/>
 <rel name="Points">
  <ref class="Point" id="1 StandaloneTCMakerConf-2-CustomTCMakerConf"/>
  <ref class="Point" id="2 StandaloneTCMakerConf-2-CustomTCMakerConf"/>
  <ref class="Point" id="3 StandaloneTCMakerConf-2-CustomTCMakerConf"/>
  <ref class="Point" id="4 StandaloneTCMakerConf-2-CustomTCMakerConf"/>
 </rel>
</obj>

<obj class="GLink" id="StandaloneTCMakerConf-2-RandomTCMakerConf">
 <rel name="From" class="Class" id="StandaloneTCMakerConf"/>
 <rel name="To" class="Class" id="RandomTCMakerConf"/>
 <rel name="Points">
  <ref class="Point" id="1 StandaloneTCMakerConf-2-RandomTCMakerConf"/>
  <ref class="Point" id="2 StandaloneTCMakerConf-2-RandomTCMakerConf"/>
  <ref class="Point" id="3 StandaloneTCMakerConf-2-RandomTCMakerConf"/>
  <ref class="Point" id="4 StandaloneTCMakerConf-2-RandomTCMakerConf"/>
 </rel>
</obj>

<obj class="GLink" id="TAAlgorithm-2-TAMakerHorizontalMuonAlgorithm">
 <rel name="From" class="Class" id="TAAlgorithm"/>
 <rel name="To" class="Class" id="TAMakerHorizontalMuonAlgorithm"/>
 <rel name="Points">
  <ref class="Point" id="1 TAAlgorithm-2-TAMakerHorizontalMuonAlgorithm"/>
  <ref class="Point" id="2 TAAlgorithm-2-TAMakerHorizontalMuonAlgorithm"/>
  <ref class="Point" id="3 TAAlgorithm-2-TAMakerHorizontalMuonAlgorithm"/>
  <ref class="Point" id="4 TAAlgorithm-2-TAMakerHorizontalMuonAlgorithm"/>
 </rel>
</obj>

<obj class="GLink" id="TAAlgorithm-2-TAMakerPrescaleAlgorithm">
 <rel name="From" class="Class" id="TAAlgorithm"/>
 <rel name="To" class="Class" id="TAMakerPrescaleAlgorithm"/>
 <rel name="Points">
  <ref class="Point" id="1 TAAlgorithm-2-TAMakerPrescaleAlgorithm"/>
  <ref class="Point" id="2 TAAlgorithm-2-TAMakerPrescaleAlgorithm"/>
  <ref class="Point" id="3 TAAlgorithm-2-TAMakerPrescaleAlgorithm"/>
  <ref class="Point" id="4 TAAlgorithm-2-TAMakerPrescaleAlgorithm"/>
 </rel>
</obj>

<obj class="GLink" id="TCAlgorithm-2-TCCustomAlgorithm">
 <rel name="From" class="Class" id="TCAlgorithm"/>
 <rel name="To" class="Class" id="TCCustomAlgorithm"/>
 <rel name="Points">
  <ref class="Point" id="1 TCAlgorithm-2-TCCustomAlgorithm"/>
  <ref class="Point" id="2 TCAlgorithm-2-TCCustomAlgorithm"/>
  <ref class="Point" id="3 TCAlgorithm-2-TCCustomAlgorithm"/>
  <ref class="Point" id="4 TCAlgorithm-2-TCCustomAlgorithm"/>
 </rel>
</obj>

<obj class="Point" id="1 CustomTCMaker-2-CustomTCMakerConf-via-configuration">
 <attr name="x" type="s16" val="136"/>
 <attr name="y" type="s16" val="24"/>
</obj>

<obj class="Point" id="1 DataProcessor-2-HSIFrameProcessor">
 <attr name="x" type="s16" val="116"/>
 <attr name="y" type="s16" val="65"/>
</obj>

<obj class="Point" id="1 DataProcessor-2-RawDataProcessor">
 <attr name="x" type="s16" val="116"/>
 <attr name="y" type="s16" val="65"/>
</obj>

<obj class="Point" id="1 DataProcessor-2-TADataProcessor">
 <attr name="x" type="s16" val="116"/>
 <attr name="y" type="s16" val="51"/>
</obj>

<obj class="Point" id="1 DataProcessor-2-TPDataProcessor">
 <attr name="x" type="s16" val="116"/>
 <attr name="y" type="s16" val="65"/>
</obj>

<obj class="Point" id="1 DataReceiverConf-2-HSI2TCTranslatorConf">
 <attr name="x" type="s16" val="12"/>
 <attr name="y" type="s16" val="51"/>
</obj>

<obj class="Point" id="1 DataReceiverConf-2-StreamEmulationParameters-via-emulation_conf">
 <attr name="x" type="s16" val="200"/>
 <attr name="y" type="s16" val="51"/>
</obj>

<obj class="Point" id="1 DataSubscriberModule-2-DataReceiverConf-via-configuration">
 <attr name="x" type="s16" val="72"/>
 <attr name="y" type="s16" val="24"/>
</obj>

<obj class="Point" id="1 FakeHSIApplication-2-FakeHSIEventGeneratorConf-via-generator">
 <attr name="x" type="s16" val="79"/>
 <attr name="y" type="s16" val="51"/>
</obj>
